### Tworzenie nowego użytkownika
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "nowyuser",
  "email": "nowyuser@example.com",
  "passwordHash": "haslo123",
  "isActive": true,
  "roles": [
    { "id": 1, "name": "ROLE_USER" }
  ]
}

### Logowanie i pobranie tokena JWT
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "nowyuser",
  "password": "haslo123"
}

### Odświeżenie tokena JWT
POST http://localhost:8080/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5Mzk5MiwiZXhwIjoxNzU4OTk0ODkyfQ.sUSffjwQ2Yyq5Uv4Xk0AAZWXRr4t5z8fJD8OHvk1zlU
Content-Type: application/json


### Dodanie subskrypcji dla użytkownika
POST http://localhost:8080/api/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5NzM4MSwiZXhwIjoxNzU4OTk4MjgxfQ.ATAuxU14_F7zdQsBp7bEgLMv7MYiDbcCNYbapGXqthw
Content-Type: application/x-www-form-urlencoded

symbol=pln&threshold=100.00

### Usunięcie subskrypcji (soft delete)
DELETE http://localhost:8080/api/subscriptions/9aabd5ac-7c7a-4bbd-ac93-c970b5c6ad21
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5NzM4MSwiZXhwIjoxNzU4OTk4MjgxfQ.ATAuxU14_F7zdQsBp7bEgLMv7MYiDbcCNYbapGXqthw

### Aktualizacja statusu subskrypcji
PUT http://localhost:8080/api/subscriptions/9aabd5ac-7c7a-4bbd-ac93-c970b5c6ad21?active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5NzM4MSwiZXhwIjoxNzU4OTk4MjgxfQ.ATAuxU14_F7zdQsBp7bEgLMv7MYiDbcCNYbapGXqthw

### Pobranie subskrypcji zalogowanego użytkownika
GET http://localhost:8080/api/subscriptions/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5NzM4MSwiZXhwIjoxNzU4OTk4MjgxfQ.ATAuxU14_F7zdQsBp7bEgLMv7MYiDbcCNYbapGXqthw
