### Tworzenie nowego użytkownika
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "nowyuser",
  "email": "nowyuser@example.com",
  "passwordHash": "haslo123",
  "isActive": true,
  "roles": [
    { "id": 1, "name": "ROLE_USER" }
  ]
}

### Logowanie i pobranie tokena JWT
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "nowyuser",
  "password": "haslo123"
}

### Odświeżenie tokena JWT
POST http://localhost:8080/api/v1/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5Mzk5MiwiZXhwIjoxNzU4OTk0ODkyfQ.sUSffjwQ2Yyq5Uv4Xk0AAZWXRr4t5z8fJD8OHvk1zlU
Content-Type: application/json


### Dodanie subskrypcji dla użytkownika
POST http://localhost:8080/api/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJub3d5dXNlciIsImlhdCI6MTc1ODk5NDE3NiwiZXhwIjoxNzU4OTk1MDc2fQ.a7NMS59AcQU02TE9640DlNhmANp4cxH-w1r4kAGiYco
Content-Type: application/x-www-form-urlencoded

symbol=btc

### Usunięcie subskrypcji (soft delete)
DELETE http://localhost:8080/api/subscriptions/{{subscriptionId}}
Authorization: Bearer {{jwt_token}}

### Aktualizacja statusu subskrypcji
PUT http://localhost:8080/api/subscriptions/{{subscriptionId}}?active=true
Authorization: Bearer {{jwt_token}}

### Pobranie subskrypcji zalogowanego użytkownika
GET http://localhost:8080/api/subscriptions/me
Authorization: Bearer {{jwt_token}}